/*
 * m_auto.h
 *
 * Hand-written machine compatibility header for PJLIB on
 * ARM Cortex-M (little endian, no MMU, no Pentium).
 *
 * This replaces the file normally generated by autoconf.
 */
#ifndef __PJ_COMPAT_M_AUTO_H__
#define __PJ_COMPAT_M_AUTO_H__

/* Machine name */
#define PJ_M_NAME               "armv8m"

/* PJLIB canonical ARM macro (see pj/config.h non-autoconf ARM branch) */
#define PJ_M_ARM7               1

/* Endianness: ARM Cortex-M is little endian (unless explicitly overridden
 * by config_site.h / compiler flags)
 */
#ifndef PJ_IS_LITTLE_ENDIAN
#   define PJ_IS_LITTLE_ENDIAN  1
#   define PJ_IS_BIG_ENDIAN     0
#endif

#define PJ_HAS_PENTIUM          0

#endif  /* __PJ_COMPAT_M_AUTO_H__ */
