/*
 * os_auto.h
 *
 * Hand-written OS compatibility header for PJLIB on FreeRTOS + newlib
 * (arm-none-eabi-gcc / Cortex-M).
 *
 * This replaces the file normally generated by autoconf. Enable it by
 * compiling pjlib with -DPJ_AUTOCONF=1 and putting this directory first
 * in the include path.
 */
#ifndef __PJ_COMPAT_OS_AUTO_H__
#define __PJ_COMPAT_OS_AUTO_H__

/* Canonical OS name */
#define PJ_OS_NAME "freertos"

/* Legacy OS macros: UNDEFINED, not 0.  pjlib uses `#if defined(PJ_WIN32)`
 * style checks in many places, so a defined-but-0 macro would wrongly select
 * the Windows code paths. */
#undef PJ_WIN64
#undef PJ_WIN32
#undef PJ_WIN32_WINNT
#undef PJ_DARWINOS
#undef PJ_LINUX
#undef PJ_BSD
#undef PJ_RTEMS
#undef PJ_SUNOS
#undef PJ_ANDROID

/* Header availability (newlib nano + lwIP compat headers in this port) */
#define PJ_HAS_ARPA_INET_H          1
#define PJ_HAS_ASSERT_H             1
#define PJ_HAS_CTYPE_H              1
#define PJ_HAS_ERRNO_H              1
#define PJ_HAS_FCNTL_H              1
#define PJ_HAS_LIMITS_H             1
#define PJ_HAS_LINUX_SOCKET_H       0
#define PJ_HAS_MALLOC_H             1
#define PJ_HAS_NETDB_H              1
#define PJ_HAS_NETINET_IN_SYSTM_H   0
#define PJ_HAS_NETINET_IN_H         1
/* lwIP has no netinet/ip.h or netinet/tcp.h; the TOS/TCP options it needs
 * are all in lwip/sockets.h. */
#define PJ_HAS_NETINET_IP_H         0
#define PJ_HAS_NETINET_TCP_H        0
#define PJ_HAS_NET_IF_H             0
#define PJ_HAS_IFADDRS_H            0
#define PJ_HAS_INTTYPES_H           1
#define PJ_HAS_SEMAPHORE_H          0
#define PJ_HAS_SETJMP_H             1
#define PJ_HAS_STDARG_H             1
#define PJ_HAS_STDDEF_H             1
#define PJ_HAS_STDIO_H              1
#define PJ_HAS_STDINT_H             1
#define PJ_HAS_STDLIB_H             1
#define PJ_HAS_STRING_H             1
#define PJ_HAS_SYS_IOCTL_H          0
/* NOTE: newlib's <sys/types.h> includes <sys/select.h> internally, so we
 * must NOT shadow it with an lwIP compat header. select()/fd_set are
 * provided via our own sock_select_lwip.c. */
#define PJ_HAS_SYS_SELECT_H         0
#define PJ_HAS_SYS_SOCKET_H         1
#define PJ_HAS_SYS_TIME_H           1
#define PJ_HAS_SYS_TIMEB_H          0
#define PJ_HAS_SYS_TYPES_H          1
#define PJ_HAS_SYS_FILIO_H          0
#define PJ_HAS_SYS_SOCKIO_H         0
#define PJ_HAS_SYS_UTSNAME_H        0
#define PJ_HAS_TIME_H               1
#define PJ_HAS_UNISTD_H             1
#define PJ_HAS_EXECINFO_H           0

#define PJ_HAS_MSWSOCK_H            0
#define PJ_HAS_WINSOCK_H            0
#define PJ_HAS_WINSOCK2_H           0
#define PJ_HAS_WS2TCPIP_H           0

/* Socket capability macros (lwIP socket layer) */
#define PJ_SOCK_HAS_IPV6_V6ONLY     0
#define PJ_SOCK_HAS_INET_ATON       1
#define PJ_SOCK_HAS_INET_PTON       1
#define PJ_SOCK_HAS_INET_NTOP       1
#define PJ_SOCK_HAS_GETADDRINFO     1
#define PJ_SOCK_HAS_SOCKETPAIR      0

/* lwIP sockaddr_in has a leading sa_len member; make pjlib's pj_sockaddr_in
 * layout-identical so the two can be cast directly. */
#define PJ_SOCKADDR_HAS_LEN         1

/* socklen_t is provided by lwIP (u32_t); prevent pj/compat/socket.h from
 * typedef'ing it as int (which would clash with lwIP's). */
#define PJ_HAS_SOCKLEN_T            1

/* Semaphores are provided by the FreeRTOS port (counting semaphores) */
#define PJ_HAS_SEMAPHORE            1

#define PJ_HAS_PTHREAD_MUTEXATTR_SETTYPE   0
#define PJ_PTHREAD_MUTEXATTR_T_HAS_RECURSIVE 0

/* errno is available from newlib */
#define PJ_HAS_ERRNO_VAR            1

#include <errno.h>

/* lwIP (with LWIP_ERRNO_STDINCLUDE=1) reports non-blocking would-block via
 * EAGAIN and non-blocking connect via EINPROGRESS (newlib errno values). */
#define PJ_HAS_SO_ERROR             0
#define PJ_BLOCKING_ERROR_VAL       EAGAIN
#define PJ_BLOCKING_CONNECT_ERROR_VAL EINPROGRESS

/* Threading is enabled */
#ifndef PJ_HAS_THREADS
#   define PJ_HAS_THREADS           1
#endif

/* Reader/writer mutex has no native implementation on FreeRTOS; the
 * generic (emulated) one would be used (os_rwmutex.c). Required macro. */
#define PJ_EMULATE_RWMUTEX          1

/* FreeRTOS allocates the task stack, not pjlib. Required macro. */
#define PJ_THREAD_SET_STACK_SIZE    0

/* atomic slist: use the cross-platform (mutex-based) implementation. */
#define PJ_ATOMIC_SLIST_IMPLEMENTATION  PJ_ATOMIC_SLIST_GENERIC

/* High resolution timer (DWT cycle counter, see os_timestamp_freertos.c) */
#define PJ_HAS_HIGH_RES_TIMER       1

#define PJ_HAS_MALLOC               1

#define PJ_OS_HAS_CHECK_STACK       0

#define PJ_HAS_LOCALTIME_R          0

#define PJ_NATIVE_STRING_IS_UNICODE 0

/* ARM is 32-bit little endian; align pools to 8 bytes */
#define PJ_POOL_ALIGNMENT           8

#define PJ_ATOMIC_VALUE_TYPE        long

#endif  /* __PJ_COMPAT_OS_AUTO_H__ */
