/*
 * pj_crypto.c - AES-128-CBC decrypt of the SIP registration password.
 *
 * Ciphertext generated by works/tools/encrypt_cred.py with the same key/IV
 * below.  Regenerate with:
 *     python works\\tools\\encrypt_cred.py "yourpass"
 * and replace s_cred_ct.  Uses the PSA cipher API (mbedtls 4.x no longer
 * ships the legacy mbedtls/aes.h).
 */
#include "pj_crypto.h"

#include "psa/crypto.h"

/* Key/IV must match works/tools/encrypt_cred.py.  Exactly 16 bytes (no NUL
 * terminator is stored in the array). */
static const uint8_t s_key[16] = "qemu-phone-cred0";
static const uint8_t s_iv[16]  = "0123456789abcdef";

/* AES-128-CBC(PKCS7) of "1234". */
static const uint8_t s_cred_ct[] = {
    0x4e, 0x16, 0x47, 0xdf, 0x17, 0x00, 0xc3, 0x16, 0x93, 0xb3, 0xe3, 0xd2,
    0x0b, 0xff, 0xee, 0xad,
};

const char *cred_get_password(void)
{
    static char s_pt[32];
    static int s_done = 0;

    if (!s_done) {
        psa_key_attributes_t attr = PSA_KEY_ATTRIBUTES_INIT;
        psa_cipher_operation_t op = PSA_CIPHER_OPERATION_INIT;
        psa_key_id_t key_id = 0;
        size_t olen1 = 0;
        size_t olen2 = 0;

        s_pt[0] = '\0';
        psa_set_key_type(&attr, PSA_KEY_TYPE_AES);
        psa_set_key_bits(&attr, 128);
        psa_set_key_usage_flags(&attr, PSA_KEY_USAGE_DECRYPT);
        psa_set_key_algorithm(&attr, PSA_ALG_CBC_PKCS7);
        if (psa_crypto_init() == PSA_SUCCESS &&
            psa_import_key(&attr, s_key, sizeof(s_key), &key_id) == PSA_SUCCESS &&
            psa_cipher_decrypt_setup(&op, key_id, PSA_ALG_CBC_PKCS7) == PSA_SUCCESS &&
            psa_cipher_set_iv(&op, s_iv, sizeof(s_iv)) == PSA_SUCCESS &&
            psa_cipher_update(&op, s_cred_ct, sizeof(s_cred_ct),
                              (uint8_t *) s_pt, sizeof(s_pt) - 1,
                              &olen1) == PSA_SUCCESS &&
            psa_cipher_finish(&op, (uint8_t *) s_pt + olen1,
                              sizeof(s_pt) - 1 - olen1,
                              &olen2) == PSA_SUCCESS) {
            s_pt[olen1 + olen2] = '\0';
        }
        psa_cipher_abort(&op);
        psa_destroy_key(key_id);
        s_done = 1;
    }
    return s_pt;
}

int cred_random_bytes(uint8_t *buf, size_t len)
{
    if (buf == NULL || len == 0) {
        return -1;
    }
    if (psa_crypto_init() != PSA_SUCCESS) {
        return -1;
    }
    if (psa_generate_random(buf, len) != PSA_SUCCESS) {
        return -1;
    }
    return 0;
}
