string(STRIP "${TARGET_PROJECT}" TARGET_PROJECT)
message(STATUS "Selected board project: [${TARGET_PROJECT}]")
if(TARGET_PROJECT STREQUAL "FreeRTOS")
    add_library(freertos_config INTERFACE)
    target_include_directories(freertos_config SYSTEM INTERFACE ${CMAKE_SOURCE_DIR}/boards/${BOARD}/FreeRTOS/application)
    add_subdirectory(FreeRTOS)
    add_library(rtos ALIAS freertos_kernel)
endif()
if(TARGET_PROJECT STREQUAL "threadx")
    set(TX_USER_FILE ${CMAKE_SOURCE_DIR}/boards/${BOARD}/threadx/application/tx_user.h)
    set(THREADX_ARCH "cortex_m33" CACHE STRING "ThreadX architecture")
    set(THREADX_TOOLCHAIN "gnu" CACHE STRING "ThreadX toolchain")
    add_subdirectory(threadx)
    add_library(rtos ALIAS threadx)
endif()
